### PR TITLE
Reduce nullability

### PR DESCRIPTION
**Pull request by kevgo**
Increase correctness by eliminating pointers.

### CODE REVIEW

**Comment by charlierudolph** [comment]
What makes you say this increases correctness?

**Comment by kevgo** [comment]
I mean it in the context of the billion dollar mistake. Something that can be nil could be nil when it shouldn't be nil. Something that cannot be nil will never be nil in those situations.

**Comment by charlierudolph** [comment]
What is the billon dollar mistake? Sure this avoid a nil reference but I feel that can be equivalent to returning the 0 or empty value version of the object and you'll get an unexpected error or result further down the road.

**Comment by charlierudolph** [comment]
What is the billon dollar mistake? Sure this avoid a nil reference but I feel that can be equivalent to returning the 0 or empty value version of the object and you'll get an unexpected error or result further down the road (which is why tests are so important).

**Comment by kevgo** [comment]
I am referring to the null reference. It's inventor, Tony Hoare, calls them his "billion dollar mistake" and [apologized for them](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions). Implicit nullability (where null can take the place of an actual instance) is an anti-pattern that undermines important type system guarantees. In our example, we have instances of `*config.Config`. If that pointer points to an actual value, it behaves correctly and provides access to the configuration settings. If that pointer is `nil`, it behaves differently and throws runtime panics when used. To be sure that these runtime panics never happen, one would have to check that the respective pointer isn't `nil` on every use of it (and use default configuration values instead). In our case, we rely on higher-level knowledge in our heads that "this pointer will never be null in real life" and we therefore don't check for `nil` at runtime. Such "manual type reasoning" is brittle, doesn't scale, and isn't documented anywhere in the codebase. This knowledge isn't available to other developers, linters, and our future selves.

By making the `Config` attribute of `ProdRepo` non-nullable, I document that every `ProdRepo` has a configuration in ways that the type checker understands and can help enforce. This removes an entire category of nil-pointer dereference errors.

**Pull request merged**
