### PR TITLE
WIP: Expose error for drivers package

### PR DESCRIPTION
**Pull request by blaggacao**
This should gradually work towards improved code coherence among drivers, those errors are all stereotypical ("typed" / "static") in nature.

### CODE REVIEW

**Comment by kevgo** [comment]
This PR seems to include the Gitea drivers. Can you clean this up? Or is this superseded by #1514?

**Comment by blaggacao** [comment]
Just missing a rebase once gitea is shipped...

**Comment by kevgo** [comment]
Okay, please comment here if you want me to 👀 at this again.

**Comment by blaggacao** [comment]
Superseded by https://github.com/git-town/git-town/pull/1518#discussion_r434976618

**Pull request closed without merging**
